# Generated by Django 5.1 on 2024-09-06 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0006_chunks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_tokens', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(choices=[(0, 'Assistant'), (1, 'User')])),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(-1, 'Failed'), (0, 'Initialized'), (1, 'Finalized'), (2, 'Processing')], default=0)),
                ('needs_context_selection', models.BooleanField(default=False)),
                ('used_context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatapp.contextselection')),
            ],
        ),
        migrations.CreateModel(
            name='ChatInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Waiting For Assitant'), (1, 'Processing'), (2, 'Waiting For User')], default=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rule_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_instance_set', to='chatapp.ruleset')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.section')),
            ],
        ),
        migrations.AddField(
            model_name='contextselection',
            name='selected_documents',
            field=models.ManyToManyField(blank=True, to='chatapp.selecteddocuments'),
        ),
    ]
