# Generated by Django 5.1 on 2024-09-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_remove_chatmessage_source_chatmessage_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selecteddocuments',
            name='document',
        ),
        migrations.AddField(
            model_name='contextselection',
            name='raw_selection',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Failed'), (0, 'Initialized'), (1, 'Finalized'), (2, 'Processing'), (3, 'Context Selected')], default=0),
        ),
    ]
