# Generated by Django 5.1 on 2024-09-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_remove_selecteddocuments_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='context_selected_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_received_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
