# Generated by Django 5.1 on 2024-09-10 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_chatmessage_context_selected_stamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=100)),
                ('exception', models.CharField(max_length=100)),
                ('traceback', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatapp.chatmessage')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatapp.chatinstance')),
            ],
        ),
    ]
