# Generated by Django 5.1 on 2024-09-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='Qdrant_db_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='Osearch_db_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='raw_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='html_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='markdown_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='raw_content',
            field=models.TextField(blank=True),
        ),
    ]
