# Generated by Django 5.1 on 2024-09-04 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_phrase_qdrant_db_id_section_osearch_db_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='extracted_information',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Section_intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.section')),
            ],
        ),
        migrations.CreateModel(
            name='Section_NER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.section')),
            ],
        ),
    ]
