# Generated by Django 5.1 on 2024-09-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_section_extracted_information_section_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='raw_pdf_process',
            field=models.TextField(blank=True),
        ),
    ]
