# Generated by Django 5.1 on 2024-09-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_raw_pdf_process'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['parent', 'page_number']},
        ),
        migrations.AlterModelOptions(
            name='phrase',
            options={'ordering': ('parent', 'phrase_order')},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('parent', 'section_order')},
        ),
    ]
