# Generated by Django 5.1 on 2024-09-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_page_options_alter_phrase_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalFile', models.CharField(max_length=255)),
            ],
        ),
    ]
