# Generated by Django 5.1 on 2024-09-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_chunks'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='num_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='num_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
