# Generated by Django 5.1 on 2024-10-03 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_linked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PDFTableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='PDFPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('top_margin', models.FloatField()),
                ('bottom_margin', models.FloatField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pdf_processor.pdfdocument')),
            ],
        ),
        migrations.CreateModel(
            name='PDFLineGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_processor.pdfpage')),
            ],
        ),
        migrations.CreateModel(
            name='PDFImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('z_index', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pdf_processor.pdfpage')),
            ],
        ),
        migrations.CreateModel(
            name='PDFPageContentOrdered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf_processor.pdfimage')),
                ('line_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf_processor.pdflinegroup')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='pdf_processor.pdfpage')),
            ],
            options={
                'ordering': ('page', 'order'),
            },
        ),
        migrations.CreateModel(
            name='LinkedPDFContentOrdered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_content', to='pdf_processor.pdfdocument')),
                ('linked_content', models.ManyToManyField(to='pdf_processor.pdfpagecontentordered')),
            ],
        ),
        migrations.CreateModel(
            name='PDFTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_processor.pdfpage')),
            ],
        ),
        migrations.AddField(
            model_name='pdfpagecontentordered',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf_processor.pdftable'),
        ),
        migrations.CreateModel(
            name='PDFTableHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cells', models.ManyToManyField(to='pdf_processor.pdftablecell')),
            ],
        ),
        migrations.CreateModel(
            name='PDFTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('cells', models.ManyToManyField(to='pdf_processor.pdftablecell')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='pdftable',
            name='rows',
            field=models.ManyToManyField(related_name='parent', to='pdf_processor.pdftablerow'),
        ),
        migrations.CreateModel(
            name='PDFText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('x', models.FloatField()),
                ('width', models.FloatField(default=100)),
                ('y', models.FloatField()),
                ('font_size', models.FloatField()),
                ('font_weight', models.CharField(max_length=50)),
                ('font_color', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='pdf_processor.pdfpage')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='pdftablecell',
            name='text',
            field=models.ManyToManyField(to='pdf_processor.pdftext'),
        ),
        migrations.AddField(
            model_name='pdflinegroup',
            name='lines',
            field=models.ManyToManyField(to='pdf_processor.pdftext'),
        ),
    ]
